### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by exander77** [gkostka/lwext4#14]
I have problem building on Windows.

I followed the MSYS guide, used:

```
make generic
cd build_generic
make
sudo make install
```

The test utility generic does not work, it seems to produce linux version.

Even after some hacking, I can't seem to open Windows volume.

**Comment by gkostka** [comment]
MYSY doesn't define macro WIN32 anymore. Here is a solution for this:
http://www.davidegrayson.com/windev/msys2/

You could fix it in lwext4 and create pull request if you like. Otherwise i will fix it soon.

Regards
GK

**Comment by exander77** [comment]
I have a few patches prepared to make it work. There are some problems in the sources too,  The utilities under Windows needs both windows and linux blockdev types.

Now I switched to crosscompile on Linux and added mingw toolchain to be able to compile it under Linux mingw.

But currently I segfault on my ext4 drive (both on Linux and Windows).

I am building my own binary to open certain drive and llist a certain directory:

```
ext4_mbr
ext4_mbr_scan:
mbr_entry 0:
	empty/unknown
mbr_entry 1:
	offeset: 0x4000000, 64MB
	size:    0x3b1980000, 15129MB
ext4_fs: l: 219   [info]  sblock features_incompatible:
ext4_fs: l: 144   filetype
ext4_fs: l: 146   recover
ext4_fs: l: 152   extents
ext4_fs: l: 158   flex_bg
ext4_fs: l: 222   [info]  sblock features_compatible:
ext4_fs: l: 177   has_journal
ext4_fs: l: 179   ext_attr
ext4_fs: l: 181   resize_inode
ext4_fs: l: 183   dir_index
ext4_fs: l: 225   [info]  sblock features_read_only:
ext4_fs: l: 189   sparse_super
ext4_fs: l: 191   large_file
ext4_fs: l: 197   gtd_csum
ext4_fs: l: 199   dir_nlink
ext4_fs: l: 201   extra_isize
ext4_fs: l: 109   [warn]  last umount error: superblock fs_error flag
ext4_jbd: l: 1065   Start of journal at trans id: 1
ext4_jbd: l: 1181   End of journal.
ext4_jbd: l: 1065   Start of journal at trans id: 1
ext4_jbd: l: 1181   End of journal.
ext4_jbd: l: 1065   Start of journal at trans id: 1
ext4_jbd: l: 1181   End of journal.
ls /srv/
Segmentation fault (core dumped)
```

**Comment by exander77** [comment]
Fixed it! That was my mistake.

**Comment by gkostka** [comment]
Good to hear that it works. Anyway, if you have those mingw relaed changes please feel free to create pull request.

Cheers

**Comment by gkostka** [comment]
Fixed https://github.com/gkostka/lwext4/pull/15
