### ISSUE TITLE
EXT4 journalling issue

### ISSUE THREAD

**Issue by rajeshvenkataraman** [gkostka/lwext4#16]
I see sometimes the ext4_fwrite() function takes really long time. I traced it down to in jbd_journal_alloc_block(). Inside this function it does this:

        /* If there is no space left, flush all journalled
         * blocks to disk first.*/
        if (journal->last == journal->start) {
                jbd_journal_purge_cp_trans(journal, true, false);
        }

This is were its taking a really long time. I made some changes to fix this delay and wanted to know if there will be any side effects due to this change.

in the ext4.c in function __ext4_trans_stop() I added the following lines

              //Flush all the journalled blocks of the previous transaction 
               diff = journal->last - journal->start;
                if(journal->last < journal->start) {
                  diff +=  jbd_get32((&journal->jbd_fs->sb), maxlen);
                }
                if(diff)
                  jbd_journal_purge_cp_trans(journal, true, false);

So instead of waiting till we run out of space purge the Journal block after each transaction. That way it does not take to long. We will never run out of journal blocks.

Thanks
Rajesh

**Comment by ngkaho1234** [comment]
It would be fine if we flush the journal immediately each time a transaction commits.

**Comment by gkostka** [comment]
Hi,

sorry for late response. Rajesh, it seems that your journal transaction is getting large. Your proposal will solve a problem of one ext4_fwrite timing. However, every ext4_fwrite has to purge transaction after your changes. So, it might be performance killer.

Maybe you could try another aproach. You could force cache flush by calling:
ext4_cache_write_back("/", false);
ext4_cache_write_back("/", true);

Code above will flush whole cache and enable writeback mode again.

https://github.com/gkostka/lwext4/blob/master/include/ext4.h#L235

**Comment by rajeshvenkataraman** [comment]
I did not understand the previous comment:

> Maybe you could try another aproach. You could force cache flush by calling:
> ext4_cache_write_back("/", false);
> ext4_cache_write_back("/", true);

Where should I call this to force cache flush? Also by the way I have not enabled the cache write back.

Rajesh

**Comment by gkostka** [comment]
> Where should I call this to force cache flush?

Ok, I thought that you are enabling cache write-back mode by hand somewhere. If not, you have to show us more code because don't get where is the problem in fact.

**Comment by gkostka** [comment]
Fixed
