### ISSUE TITLE
number of groups computation issue

### ISSUE THREAD

**Issue by rajeshvenkataraman** [gkostka/lwext4#17]
In the create_fs_aux_info() the number of groups is calculated in the code as below
aux_info->groups = (uint32_t)EXT4_DIV_ROUND_UP(aux_info->len_blocks - aux_info->first_data_block, info->blocks_per_group); file ext4_mkfs.c line 154.
 But in this calculation the  bd->part_offset value is never considered. For example If I have some other data in the first 128 M bytes of  eMMC flash. I set the part_offset to 128 M for the partition. So I expect the filesystem to start after the first 128 M bytes. But this is not considered in the ext4_mkfs() even if the ext4_blockdev *bd has part_offset set to 128 M Bytes. Can this be added to computing the number of groups? Or is there any other better way to offset the filesystem sector address.

static int create_fs_aux_info(struct fs_aux_info *aux_info,
			      struct ext4_mkfs_info *info)
{
	aux_info->first_data_block = (info->block_size > 1024) ? 0 : 1;
	aux_info->len_blocks = info->len / info->block_size;
	aux_info->inode_table_blocks = EXT4_DIV_ROUND_UP(info->inodes_per_group *
			info->inode_size, info->block_size);
	aux_info->groups = (uint32_t)EXT4_DIV_ROUND_UP(aux_info->len_blocks -
aux_info->first_data_block, info->blocks_per_group);

**Comment by gkostka** [comment]
Hi, I don't think that bd->part_offset should be considered in block group calculations or any other in mkfs module. So, if you are setting  bd->part_offset manually, make sure that part_size and and lg_bcnt fields are modified too.

 bd->part_offset = 128 * 1024 * 1024;
 bd->part_size -= 128 * 1024 * 1024;
 ext4_block_set_lb_size(bd, 4096);    //Set your desired block size here :)

After these modifications ext4_mkfs should calculate correctly partition parameters. Note that, if your disk has MBR layout, you could use ext4_mbr_scan to get all partition block devices.

**Comment by gkostka** [comment]
Response timeout.
