### ISSUE TITLE
Need new functions

### ISSUE THREAD

**Issue by Antinachai** [gkostka/lwext4#18]
Hi.
Sorry for my English..
Need new functions in ext4.h
int ext4_file_GET_atime(const char *path, uint32_t atime);
int ext4_file_GET_mtime(const char *path, uint32_t atime);
int ext4_file_GET_ctime(const char *path, uint32_t atime);

int ext4_GET_mode_bits(const char *path, const uint32_t mode); -> this function read mode bits to uint32_t mode by const char *path
int ext4_get_sblock(const char *path, const struct ext4_inode *inode); -> this function read inode by const char *path to struct ext4_inode *inode
Big Thanks for help.

**Comment by Antinachai** [comment]
10 days passed...

**Comment by gkostka** [comment]
We have to make something clear here. This is open source and I'm making lwext4 in my free time. Recently I was busy and did not find time to do this. So, you have to be patient and stop behaving like you have right to demand something here. You could also implement it by yourself because it is really simple task (copy-paste in fact).

**Comment by Antinachai** [comment]
Please excuse me
Please do not be offended
If need any time - for release this functions - is very good. 
I'll wait
thank you very much for your understanding

B.R. Aleksandr
===
Уважаемый Грегорз!
Извиняюсь, всё что написано выше, есть результат непонимания перевода.
Я надеюсь вы поймете данный текст, 
Я понимаю что это Ваше хобби, и я ни каким образом не имею права требовать что либо от вас. 
К тому же ГитХаб - это открытый проект.
Я всего лишь просил реализовать данные функции, я просто глупый неудачный программист. Не особо понимающий язык С++
Я очень благодарен Вам за ваши труды, и мне очень стыдно что на Английском языке это выглядит как будто я требовал от вас писать код.
Не обижайтесь пожалуйста. Я не желал обидеть Вас и уж тем более что либо требовать.
Огромное спасибо за понимание!

**Comment by gkostka** [comment]
Implemented: https://github.com/gkostka/lwext4/commit/83e87bd113dc957d4a9185cd6ff67c2268602436

**Comment by Antinachai** [comment]
Hi.
Dear Grzegorz
BIG Thahks for Implement this functions! 
One Question...
Please Check it:
for example 
function int ext4_atime_get(const char *path, uint32_t *atime)
include this code:
	if (mp->fs.read_only)
		return EROFS;

this is correct?
if FS is read only - this deny reading mode/owner/atime/mtime/ctime ?
i see ERR 30 while reading this data from R/O FS

B.R. Aleksandr.

**Comment by gkostka** [comment]
Yes. You are correct. Fixed here: https://github.com/gkostka/lwext4/commit/ec5adbc6757768592da6917a07f6bc1c588ad2f8

Thanks
