### ISSUE TITLE
add function, please

### ISSUE THREAD

**Issue by tihiygrom** [gkostka/lwext4#20]
in the module "ext4.c" :
int ext4_get_inode(const char *path, struct ext4_inode *inode)
{
    struct ext4_inode_ref inode_ref;
	struct ext4_mountpoint *mp = ext4_get_mount(path);
	ext4_file f;
	int r;

	if (!mp)
		return ENOENT;

	EXT4_MP_LOCK(mp);

	r = ext4_generic_open2(&f, path, O_RDONLY, EXT4_DE_UNKNOWN, NULL, NULL);
	if (r != EOK)
		goto Finish;

	r = ext4_fs_get_inode_ref(&mp->fs, f.inode, &inode_ref);
	if (r != EOK)
		goto Finish;

	memcpy(inode, inode_ref.inode, sizeof(struct ext4_inode));
	r = ext4_fs_put_inode_ref(&inode_ref);

	Finish:
	EXT4_MP_UNLOCK(mp);

	return r;
}

in the module "ext4.h" :
int ext4_get_inode(const char *path, struct ext4_inode *inode);

**Comment by gkostka** [comment]
Hi, there was similar function (ext4_fill_raw_inode). I've made some style improvements and you could find desired function here:
https://github.com/gkostka/lwext4/blob/master/src/ext4.c#L1534

(better named and located in header file).

**Comment by tihiygrom** [comment]
thanks :) I have not noticed this function
