### ISSUE TITLE
`cortex-m4.cmake` assumes hardware floating point

### ISSUE THREAD

**Issue by cpavlina** [gkostka/lwext4#23]
This line in `cortex-m4.cmake` assumes the device has a hardware FPU:

    set(VFP_FLAGS "-mfloat-abi=hard -mfpu=fpv4-sp-d16")

This is only the case for Cortex-M4F. Non-"F" Cortex-M4 should be built with the same VFP_FLAGS as Cortex-M3 (i.e. empty string).

**Comment by gkostka** [comment]
You are correct. I will fix it in a free moment. Thanks:)

**Comment by gkostka** [comment]
Fixed here: https://github.com/gkostka/lwext4/commit/2a4f69fbabf98920717366cd574f0d4aba1aa3a1
