### ISSUE TITLE
Please add functions

### ISSUE THREAD

**Issue by Antinachai** [gkostka/lwext4#24]
Please add two functions..
 
@param   path Path to file.
@param   result output.
@return  Standard error code. 
int ext4_file_exists(const char *path, bool on);
 
@param   path Path to directury.
@param   result output.
@return  Standard error code. 
int ext4_dir_exists(const char *path, bool on);
 
Functions set bool on to TRUE if file/dir exist on by path 
Big Thanks!

**Comment by gkostka** [comment]
https://github.com/gkostka/lwext4/commit/c8978f9dba53333004f3f20e5acc57df8867dc16
