### ISSUE TITLE
ext4_fseek offset is unsigned

### ISSUE THREAD

**Issue by cpavlina** [gkostka/lwext4#25]
Generally `fseek` takes a signed offset; this allows seeking backward when using `SEEK_CUR` and `SEEK_END`. `ext4_fseek` uses a `uint64_t` offset, so it's not possible to seek backwards unless you do the math manually with `ext4_ftell` and then use `SEEK_SET`.

**Comment by gkostka** [comment]
Hi,

you are correct. I will fix it soon.
