### ISSUE TITLE
Filesystem Corruption

### ISSUE THREAD

**Issue by rajeshvenkataraman** [gkostka/lwext4#27]
I am using the following configuration for the EXT4

Inode Count	229376
Free Inode Count	228824
Block Count	917504
Free Block Count	3126
Block Size	1024
Block Group Count	112
Blocks Per Group	8192
Inodes Per Group	2048

After running the filesystem with generating new files and deleting old files, the filesystem gets corrupted. There are free blocks (The Free Block Count is 3126). But the write fails with ENOSPC return code. The fsck.ext4 shows lots of errors. Any ideas why the filesystem would fail like this? I have attached the log of the fsck.ext4

[fsck.txt](https://github.com/gkostka/lwext4/files/998067/fsck.txt)

**Comment by gkostka** [comment]
Hi, you have to provide some code to reproduce potential error. It might be hundred of reasons. Without more information I can't help.

**Comment by rajeshvenkataraman** [comment]
I am running the filesystem on a embedded application that continuously collects data to files and deletes the older files on storage full. I see the corruption after testing for few days with power fails. I don't know how to exactly reproduce the problem. So I was looking at the journalling code and had few question. In the ext4_generic_open2() function the ext4_trans_start() is called in the beginning and ext4_trans_stop() is called at the end. But this function is called inside ext4_frename(). The ext4_frename() also calls the ext4_trans_start() and ext4_trans_stop(). But will the ext4_generic_open2() function call, stop the transactions prematurely?

**Comment by rajeshvenkataraman** [comment]
I will try out the fix and let you know. I also saw another strange behavior. The Journalling blocks keeps increasing after a ext4_dir_mk() operation and does not purge. But after a power-fail and remounting the filesystem the Journalling blocks does not increase and gets purged frequently. Is this behavior normal?

After directory create (Case were the purge is never called)
Creating Directory
Journal commit 
 __jbd_journal_commit_trans
JAlloc block last:1 start:1
JAlloc block last:2 start:1
JAlloc block last:3 start:1
JAlloc block last:4 start:1
JAlloc block last:5 start:1
JAlloc block last:6 start:1
JAlloc block last:7 start:1
JAlloc block last:8 start:1
JAlloc block last:9 start:1
jbd_trans_write_commit_block
JAlloc block last:10 start:1
Queue empty trans->data_cnt:8 tarns->start_iblock:1
Create Directory Done
Journal commit 
__jbd_journal_commit_trans
JAlloc block last:11 start:1
JAlloc block last:12 start:1
JAlloc block last:13 start:1
JAlloc block last:14 start:1
JAlloc block last:15 start:1
JAlloc block last:16 start:1
JAlloc block last:17 start:1
JAlloc block last:18 start:1
JAlloc block last:19 start:1
jbd_trans_write_commit_block
JAlloc block last:20 start:1
Queue not empty
Journal commit 
__jbd_journal_commit_trans
JAlloc block last:21 start:1
JAlloc block last:22 start:1
JAlloc block last:23 start:1
JAlloc block last:24 start:1
JAlloc block last:25 start:1
JAlloc block last:26 start:1
JAlloc block last:27 start:1
JAlloc block last:28 start:1
jbd_trans_write_commit_block
JAlloc block last:29 start:1
Queue not empty
Journal commit 
__jbd_journal_commit_trans
JAlloc block last:30 start:1
JAlloc block last:31 start:1


Journal Purging frequently:
JAlloc block last :5163 start:5163
JAlloc block last:5164 start:5163
JAlloc block last:5165 start:5163
JAlloc block last:5166 start:5163
JAlloc block last:5167 start:5163
jbd_trans_write_commit_block
JAlloc block last:5168 start:5163
Queue empty trans->data_cnt:4 trans->start_iblock:5163
Journal commit 
jbd_journal_purge_cp_trans 
jbd_journal_purge_cp_trans done
Journal commit 
JAlloc block last:5169 first:5169
JAlloc block last:5170 first:5169
JAlloc block last:5171 first:5169
JAlloc block last:5172 first:5169
jbd_trans_write_commit_block
JAlloc block last:5173 first:5169
Queue empty tarns->data_cnt:3 tarns->start_iblock:5169
jbd_journal_purge_cp_trans

**Comment by gkostka** [comment]
Hi, could you push the code with debug printfs code? Hard to figure out where you added them. Is latest fix helped?

**Comment by rajeshvenkataraman** [comment]
Here is the code with debug print

void
jbd_journal_purge_cp_trans(struct jbd_journal *journal,
                           bool flush,
                           bool once)
{
        struct jbd_trans *trans;
        tprintf(DBG_RTFS, "jbd_journal_purge_cp_trans \r\n");
        while ((trans = TAILQ_FIRST(&journal->cp_queue))) {
                 tprintf(DBG_RTFS, "data cnt %d\r\n", trans->data_cnt);
                if (!trans->data_cnt) {
                        TAILQ_REMOVE(&journal->cp_queue,
                                        trans,
                                        trans_node);
                        jbd_journal_skip_pure_revoke(journal, trans);
                } else {
                        tprintf(DBG_RTFS, "purge %d\r\n", journal->start);
                        if (trans->data_cnt ==
                                        trans->written_cnt) {
                                journal->start =
                                        trans->start_iblock +
                                        trans->alloc_blocks;
                                wrap(&journal->jbd_fs->sb,
                                                journal->start);
                                journal->trans_id =
                                        trans->trans_id + 1;
                                TAILQ_REMOVE(&journal->cp_queue,
                                                trans,
                                                trans_node);
                                jbd_journal_free_trans(journal,
                                                trans,
                                                false);
                                jbd_journal_write_sb(journal);
                        } else if (!flush) {
                                journal->start =
                                        trans->start_iblock;
                                wrap(&journal->jbd_fs->sb,
                                                journal->start);
                                journal->trans_id =
                                        trans->trans_id;
                                jbd_journal_write_sb(journal);
                                break;
                        } else
                                jbd_journal_flush_trans(trans);
                }
                if (once)
                        break;
        }
        tprintf(DBG_RTFS, "jbd_journal_purge_cp_trans done\r\n");
}

static uint32_t jbd_journal_alloc_block(struct jbd_journal *journal,
                                        struct jbd_trans *trans)
{
        uint32_t start_block;

        tprintf(DBG_RTFS, "JAlloc block last:%d first:%d\r\n", journal->last, journal->start);
        start_block = journal->last++;
        trans->alloc_blocks++;
        wrap(&journal->jbd_fs->sb, journal->last);

        /* If there is no space left, flush just one journalled
         * transaction.*/
        if (journal->last == journal->start) {
                jbd_journal_purge_cp_trans(journal, true, true);
                ext4_assert(journal->last != journal->start);
        }

        return start_block;
}

/**@brief  Write commit block for a transaction
 * @param  trans transaction
 * @return standard error code*/
static int jbd_trans_write_commit_block(struct jbd_trans *trans)
{
        int rc;
        struct ext4_block block;
        struct jbd_commit_header *header;
        uint32_t commit_iblock;
        struct jbd_journal *journal = trans->journal;

        tprintf(DBG_RTFS, "jbd_trans_write_commit_block\r\n");
        commit_iblock = jbd_journal_alloc_block(journal, trans);

        rc = jbd_block_get_noread(journal->jbd_fs, &block, commit_iblock);
        if (rc != EOK)
                return rc;

        header = (struct jbd_commit_header *)block.data;
        jbd_set32(&header->header, magic, JBD_MAGIC_NUMBER);
        jbd_set32(&header->header, blocktype, JBD_COMMIT_BLOCK);
        jbd_set32(&header->header, sequence, trans->trans_id);

        if (JBD_HAS_INCOMPAT_FEATURE(&journal->jbd_fs->sb,
                                JBD_FEATURE_COMPAT_CHECKSUM)) {
                jbd_set32(header, chksum_type, JBD_CRC32_CHKSUM);
                jbd_set32(header, chksum_size, JBD_CRC32_CHKSUM_SIZE);
                jbd_set32(header, chksum[0], trans->data_csum);
        }
        jbd_commit_csum_set(journal->jbd_fs, header);
        ext4_bcache_set_dirty(block.buf);
        ext4_bcache_set_flag(block.buf, BC_TMP);
        rc = jbd_block_set(journal->jbd_fs, &block);
        return rc;
}

static void jbd_trans_end_write(struct ext4_bcache *bc __unused,
                          struct ext4_buf *buf,
                          int res,
                          void *arg)
{
....
                    if (first_in_queue) {
                        tprintf(DBG_RTFS, " journal->start %d\r\n",  journal->start);
                        journal->start = trans->start_iblock +
                                trans->alloc_blocks;
                        wrap(&journal->jbd_fs->sb, journal->start);
...
}
static int __jbd_journal_commit_trans(struct jbd_journal *journal,
                                      struct jbd_trans *trans)
{
        int rc = EOK;
        uint32_t last = journal->last;
        struct jbd_revoke_rec *rec, *tmp;

        tprintf(DBG_RTFS, "__jbd_journal_commit_trans\r\n");
        trans->trans_id = journal->alloc_trans_id;
        rc = jbd_journal_prepare(journal, trans);
...
...
               if (TAILQ_EMPTY(&journal->cp_queue)) {
                /*
                 * This transaction is going to be the first object in the
                 * checkpoint queue.
                 * When the first transaction in checkpoint queue is completely
                 * written to disk, we shift the tail of the log to right.
                 */
                tprintf(DBG_RTFS, "Queue empty %d:%d\r\n", trans->data_cnt, trans->start_iblock);
                if (trans->data_cnt) {
                        journal->start = trans->start_iblock;
                        wrap(&journal->jbd_fs->sb, journal->start);
                        journal->trans_id = trans->trans_id;
                        jbd_journal_write_sb(journal);
                        jbd_write_sb(journal->jbd_fs);
                        TAILQ_INSERT_TAIL(&journal->cp_queue, trans,
                                        trans_node);
                        jbd_journal_cp_trans(journal, trans);
                } else {
                        tprintf(DBG_RTFS, "Commit %d\r\n", trans->alloc_blocks);
                        journal->start = trans->start_iblock +
                                trans->alloc_blocks;
                        wrap(&journal->jbd_fs->sb, journal->start);
                        journal->trans_id = trans->trans_id + 1;
                        jbd_journal_write_sb(journal);
                        jbd_journal_free_trans(journal, trans, false);
                }
        } else {
                tprintf(DBG_RTFS, "Queue not empty\r\n");
                /* No need to do anything to the JBD superblock. */
                TAILQ_INSERT_TAIL(&journal->cp_queue, trans,
......
}

I am running a file system with the previous fix for 3 days and have not see the issue so far. I will run it for 2 more days as I saw the problem earlier after 5 days.

**Comment by gkostka** [comment]
Hi, any updates? Does the problem still exists?

**Comment by rajeshvenkataraman** [comment]
Yes I am still seeing problems. I am unable to figure out exactly what operations cause this problem. I am still looking in the code.

I saw something interesting in the ext4.c. In some functions the order is as follows

ext4_trans_start(f->mp);
...
ext4_block_cache_write_back(f->mp->fs.bdev, 1);
...
ext4_block_cache_write_back(f->mp->fs.bdev, 0);
...
ext4_trans_stop(f->mp);

But in some functions the order is different

ext4_block_cache_write_back(mp->fs.bdev, 1);
...
ext4_trans_start(f->mp);
...
ext4_trans_stop(f->mp);
...
ext4_block_cache_write_back(mp->fs.bdev, 0);

Does the order matter between starting/stopping transactions and starting/stopping write back cache mode?

**Comment by gkostka** [comment]
Hi, sorry for late reply. I don't think that order matter in this case. I'm running out of ideas what could be wrong here. There are also two fixes related to cache invalidation. You could try to eliminate some complex functions from your code. IMO **ext4_dir_rm** is the most suspicious function. You could definitely live without this method (just delete files one by one).

**Comment by rajeshvenkataraman** [comment]
I am running the the two fixes related to cache invalidation. I am checking for the number of journalling block used using the code below in ext4_mount_point_stats(). I see that this number goes back to zero most of the time. In our system when we delete directory we delete all the files before deleting the directory. But  after the ext4_dir_rm() the used_journal_blocks keeps increasing. It reaches the maximum blocks and keeps purging one block when necessary in the jbd_journal_alloc_block(). Is this the expected behavior after a ext4_dir_rm()?


stats->used_journal_blocks = mp->jbd_journal.last - mp->jbd_journal.start;
if(stats->used_journal_blocks <0)
  stats->used_journal_blocks +=  (jbd_get32((&mp->jbd_fs.sb), maxlen));

**Comment by ngkaho1234** [comment]
Hi rajeshvenkataraman,

Sorry for the delay. I took some times today trying to nail down the issue. After some investigation in operations like  file/directory creation, i think the phenomenkn you have seen is actually because the block that journal inode(8th inode) resides in the same place as the 12th inode, which is usually the first inode you get when you create a node on a freshly made filesystem (4096 bytes as block size, journalling enabled). As a result, the first block of inode table will be pinned permanently unless you shutdown the journal. Since this block is dirties, it will be written to the journal. However, as it is pinned due to journal inode being loaded, it will be flushed only when the journal is full.

**Comment by ngkaho1234** [comment]
Hello @rajeshvenkataraman . Please have a look at https://github.com/ngkaho1234/lwext4/tree/for-grzegorz and see if that fixes the corruption problem after power loss.

**Comment by gkostka** [comment]
Hi @rajeshvenkataraman. Have you performed tests? Does the problem still exist?

**Comment by rajeshvenkataraman** [comment]
I have been running the tests on the filesystem and I have not seen that corruption so far. I will continue to run the tests till Monday and let you know the results.

**Comment by rajeshvenkataraman** [comment]
I am not seeing any corruption issue after the last fix.
