### ISSUE TITLE
Question regarding ext4_mkfs() and ext4_recover()

### ISSUE THREAD

**Issue by rajeshvenkataraman** [gkostka/lwext4#29]
I am seeing a problem in the ext4_recover(). It is returning a value of 5 (EIO). This happened when the ext4_recover() was called right after the after a ext4_mkfs() and ext4_mount().  At this time after a ext4_mkfs() is called there should not be anything to recover.  It just happened once and I cannot reproduce it again. Looks like the ext4_recover() is getting some old stale journal data from the eMMC. Is that possible? I am looking at create_journal_inode()  and in that function in the loop below we are calling ext4_block_get() and clearing only sizeof(struct jbd_sb) and not the whole block(In my case blocksize is 4K). Do we need to clear the whole block?
```
 while (blocks_count++ < info->journal_blocks)
        {
                ext4_fsblk_t fblock;
                ext4_lblk_t iblock;
                struct ext4_block blk;

                ret = ext4_fs_append_inode_dblk(&inode_ref, &fblock, &iblock);
                if (ret != EOK)
                        goto Finish;

                if (iblock != 0)
                        continue;

                ret = ext4_block_get(fs->bdev, &blk, fblock);
                if (ret != EOK)
                        goto Finish;

                **memset(blk.data, 0, info->block_size);**
                struct jbd_sb * jbd_sb = (struct jbd_sb * )blk.data;
                _//memset(jbd_sb, 0, sizeof(struct jbd_sb));_

                jbd_sb->header.magic = to_be32(JBD_MAGIC_NUMBER);
                jbd_sb->header.blocktype = to_be32(JBD_SUPERBLOCK_V2);
                jbd_sb->blocksize = to_be32(info->block_size);
                jbd_sb->maxlen = to_be32(info->journal_blocks);
                jbd_sb->nr_users = to_be32(1);
                jbd_sb->first = to_be32(1);
                jbd_sb->sequence = to_be32(1);

                ext4_bcache_set_dirty(blk.buf);
                ret = ext4_block_set(fs->bdev, &blk);
                if (ret != EOK)
                        goto Finish;
        }
```

**Comment by gkostka** [comment]
1. EIO indicates problems with your IO functions block_read/write. I would try to find issues there. There is ne easy answer for one time error which happened on your machine. Sorry.
2. Yes, you are correct. However, it is not big performance killer IMO. Create pull request for this if you like:)

Cheers

**Comment by gkostka** [comment]
Timeout.
