### ISSUE TITLE
assert() in 'Release' build

### ISSUE THREAD

**Issue by raandoom** [gkostka/lwext4#30]
In 'ext4_journal.c' at line 1333:
```
			struct ext4_block jbd_block = EXT4_BLOCK_ZERO();
			ext4_assert(jbd_block_get(journal->jbd_fs,
						&jbd_block,
						jbd_buf->jbd_lba) == EOK);
			memcpy(tmp_data, jbd_block.data,
					journal->block_size);
```
After _EXT4_BLOCK_ZERO()_ all members in _jbd_block_ has zero values. In 'Release' build assert() does nothing and _jbd_block_get()_ never called. After that _memcpy()_ crashes because _jbd_block.data_ is zero.

I think it is wrong to put function calls like that into _assert()_.
Same strange places I found at lines 1557 and 1560.

**Comment by gkostka** [comment]
Hi, you are correct. Could you open PR for this? Thanks!

**Comment by gkostka** [comment]
Fixed here https://github.com/gkostka/lwext4/commit/6e0a9f748f820da22b1dfcb8ddf12b2247409f5d
Thanks!
